apiVersion: v1
kind: Secret
metadata:
  name: private-registry-key
  namespace: development
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6IHsgIjEwLjU0LjU2LjM5OjUwMDAiOiB7ICJhdXRoIjogIlpYUjFaR2xoYm5RNlpYUjFaR2xoYm5RPSJ9fX0=

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-ip
  namespace: development
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ms-ip
  template:
    metadata:
      labels:
        app: ms-ip
    spec:
      containers:
      - name: ms-ip
        image: 10.54.56.39:5000/test:0.0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: private-registry-key
  
